SCREEN_WIDTH = 720
SCREEN_HEIGHT = 720
FPS = 60
player_speed = 5
player_position = [SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2]
player_vulnerable = True
vulnerable_timer = 2000 #in milliseconds
BACKGROUND_COLOUR = (40, 40, 40)
PLAYER_SIZE = [42, 56] #width and height of the player hitbox
TITLE = "FRONTROOMS"
player_health = 100